version: '4'
services:
  laravel:
    build:
      dockerfile: 'Dockerfile'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_LARAVEL}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${LARAVEL_HOST_HTTP_PORT}:80'
volumes: {}
